[project]
name = "liga_brasileira"
version = "0.1.0"
authors = [
    { name = "Projeto Liga" }
]
requires-python = ">=3.8"
dependencies = [
    "Pillow",
    "numpy",
    "pandas",
]

[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"
